
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN BREAK CLOSECORCHETE COMMA DIVIDE DO FI GORP GT GTE ID IF LPARENT LT LTE MINUS NE NUMBER OD ODD OPENCORCHETE PLUS PROC PROG RPARENT SEMMICOLOM SPACE TIMES UPDATE VAR WHILEprogram : PROGprogram : PROG variable proc GORPprogram : PROG variable proc proc GORPprogram : PROG variable proc proc proc GORPvariable : VAR ID COMMA ID COMMA ID SEMMICOLOMvariable : ID ASSIGN NUMBER SEMMICOLOMproc : PROC ID LPARENT ID COMMA ID RPARENT statement procproc : PROC ID LPARENT RPARENT OPENCORCHETE statement CLOSECORCHETEproc : OPENCORCHETE proc variable proc CLOSECORCHETEproc : PROC ID LPARENT RPARENT OPENCORCHETE if CLOSECORCHETEproc : ID LPARENT NUMBER COMMA NUMBER RPARENT SEMMICOLOMproc : ID LPARENT NUMBER COMMA NUMBER RPARENT statement : while if : IF condition  OPENCORCHETE statement CLOSECORCHETE  FIwhile : WHILE LPARENT ID LPARENT ID COMMA NUMBER RPARENT RPARENT DO do OD  condition : LPARENT ID LPARENT ID COMMA NUMBER RPARENT RPARENTdo :  OPENCORCHETE ID LPARENT ID COMMA NUMBER RPARENT CLOSECORCHETE statement : OPENCORCHETE ID LPARENT ID RPARENT SEMMICOLOM ID LPARENT ID RPARENT SEMMICOLOM ID LPARENT ID RPARENT CLOSECORCHETE statement : ID LPARENT ID COMMA NUMBER RPARENT'
    
_lr_action_items = {'PROG':([0,],[2,]),'$end':([1,2,13,20,26,],[0,-1,-2,-3,-4,]),'VAR':([2,16,35,45,50,51,55,62,],[4,4,-9,-12,-8,-10,-11,-7,]),'ID':([2,3,4,6,7,9,12,16,17,21,23,25,31,32,33,35,39,42,45,46,47,48,50,51,53,54,55,56,58,59,62,66,67,73,74,81,89,91,93,95,96,101,],[5,8,10,8,14,8,8,5,24,27,8,-6,36,37,38,-9,49,-13,-12,-5,38,57,-8,-10,60,61,-11,8,64,38,-7,71,72,-19,78,84,92,94,-15,97,98,-18,]),'PROC':([3,6,9,12,23,25,35,42,45,46,50,51,55,56,62,73,93,101,],[7,7,7,7,7,-6,-9,-13,-12,-5,-8,-10,-11,7,-7,-19,-15,-18,]),'OPENCORCHETE':([3,6,9,12,23,25,28,33,35,42,45,46,47,50,51,52,55,56,59,62,73,85,88,93,101,],[9,9,9,9,9,-6,33,39,-9,-13,-12,-5,39,-8,-10,59,-11,9,39,-7,-19,-16,91,-15,-18,]),'ASSIGN':([5,],[11,]),'GORP':([6,12,19,35,45,50,51,55,62,],[13,20,26,-9,-12,-8,-10,-11,-7,]),'LPARENT':([8,14,38,43,44,49,60,61,78,92,94,],[15,21,48,53,54,58,66,67,81,95,96,]),'COMMA':([10,22,24,27,57,71,72,98,],[17,29,31,32,63,76,77,100,]),'NUMBER':([11,15,29,63,76,77,100,],[18,22,34,68,79,80,102,]),'SEMMICOLOM':([18,36,45,69,87,],[25,46,55,74,89,]),'RPARENT':([21,34,37,64,68,79,80,82,83,84,97,102,],[28,45,47,69,73,82,83,85,86,87,99,103,]),'CLOSECORCHETE':([30,35,40,41,42,45,50,51,55,62,65,73,75,93,99,101,103,],[35,-9,50,51,-13,-12,-8,-10,-11,-7,70,-19,-14,-15,101,-18,104,]),'IF':([33,],[43,]),'WHILE':([33,47,59,],[44,44,44,]),'FI':([70,],[75,]),'DO':([86,],[88,]),'OD':([90,104,],[93,-17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'variable':([2,16,],[3,23,]),'proc':([3,6,9,12,23,56,],[6,12,16,19,30,62,]),'statement':([33,47,59,],[40,56,65,]),'if':([33,],[41,]),'while':([33,47,59,],[42,42,42,]),'condition':([43,],[52,]),'do':([88,],[90,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROG','program',1,'p_progs','parser.py',86),
  ('program -> PROG variable proc GORP','program',4,'p_progf','parser.py',90),
  ('program -> PROG variable proc proc GORP','program',5,'p_progf2','parser.py',94),
  ('program -> PROG variable proc proc proc GORP','program',6,'p_progf3','parser.py',99),
  ('variable -> VAR ID COMMA ID COMMA ID SEMMICOLOM','variable',7,'p_variable','parser.py',103),
  ('variable -> ID ASSIGN NUMBER SEMMICOLOM','variable',4,'p_variable1','parser.py',107),
  ('proc -> PROC ID LPARENT ID COMMA ID RPARENT statement proc','proc',9,'p_PROC','parser.py',109),
  ('proc -> PROC ID LPARENT RPARENT OPENCORCHETE statement CLOSECORCHETE','proc',7,'p_PROC1','parser.py',113),
  ('proc -> OPENCORCHETE proc variable proc CLOSECORCHETE','proc',5,'p_PROC2','parser.py',117),
  ('proc -> PROC ID LPARENT RPARENT OPENCORCHETE if CLOSECORCHETE','proc',7,'p_PROC3','parser.py',121),
  ('proc -> ID LPARENT NUMBER COMMA NUMBER RPARENT SEMMICOLOM','proc',7,'p_PROC4','parser.py',125),
  ('proc -> ID LPARENT NUMBER COMMA NUMBER RPARENT','proc',6,'p_PROC5','parser.py',128),
  ('statement -> while','statement',1,'p_statement1','parser.py',130),
  ('if -> IF condition OPENCORCHETE statement CLOSECORCHETE FI','if',6,'p_if','parser.py',138),
  ('while -> WHILE LPARENT ID LPARENT ID COMMA NUMBER RPARENT RPARENT DO do OD','while',12,'p_While','parser.py',142),
  ('condition -> LPARENT ID LPARENT ID COMMA NUMBER RPARENT RPARENT','condition',8,'p_condition','parser.py',146),
  ('do -> OPENCORCHETE ID LPARENT ID COMMA NUMBER RPARENT CLOSECORCHETE','do',8,'p_do','parser.py',148),
  ('statement -> OPENCORCHETE ID LPARENT ID RPARENT SEMMICOLOM ID LPARENT ID RPARENT SEMMICOLOM ID LPARENT ID RPARENT CLOSECORCHETE','statement',16,'p_statement','parser.py',153),
  ('statement -> ID LPARENT ID COMMA NUMBER RPARENT','statement',6,'p_statement2','parser.py',157),
]
